server:
  port: 8848

spring:
  # rabbitmq相关配置
  rabbitmq:
    host: www.tracys.cn
    username: tracy
    password: GONGRAN0812qweabc!
    port: 6012
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50
  application:
    name: cloud-manager-auth-server

mybatis:
  # 指定映射配置文件路径
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
