server:
  port: 8848

spring:
  # redis相关配置
  redis:
    host: 39.97.102.209
    password: GONGRAN0812
    database: 2
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
  # rabbitmq相关配置
  rabbitmq:
    host: www.tracys.cn
    username: tracy
    password: GONGRAN0812qweabc!
    port: 6012
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50
  application:
    name: cloud-manager-auth-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    inetutils:
      timeout-seconds: 10

mybatis:
  # 指定映射配置文件路径
  mapper-locations: classpath:mapper/*.xml



ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
