spring:
  # 指定上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # redis相关配置
  redis:
    host: 39.97.102.209
    password: GONGRAN0812
    database: 2
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0

  # rabbitmq相关配置
  rabbitmq:
    host: www.tracys.cn
    username: tracy
    password: GONGRAN0812qweabc!
    port: 6012
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50

mybatis:
  # 指定映射配置文件路径
  mapper-locations: classpath:mapper/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql