spring:
  application:
    name: springcloud-tqms-menu
server:
  port: 8100
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 服务注册到哪个 Eureka注册中心
  instance:
    instance-id: springcloud-tqms-menu-eureka  #修改该服务在 服务端的监控页面中的status状态名称
