spring:
  application:
    name: CLOUD-MANAGER-menu-SERVER
    # redis相关配置
  redis:
    host: 39.97.102.209
    password: GONGRAN0812
    database: 2
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
feign:
  hystrix:
    enabled: true
server:
  port: 8101
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 服务注册到哪个 Eureka注册中心
  instance:
    instance-id: springcloud-tqms-menu-eureka  #修改该服务在 服务端的监控页面中的status状态名称
