server:
  port: 8001

spring:
  # 指定上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # redis相关配置
  redis:
    host: 39.97.102.209
    password: GONGRAN0812
    database: 2
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0

  # rabbitmq相关配置
  rabbitmq:
    host: www.tracys.cn
    username: tracy
    password: GONGRAN0812qweabc!
    port: 6012
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 50
#  elasticsearch:
#    rest:
#      username: elastic
#      password: GONGRAN0812a
#      uris: http://es-cn-n6w1ym8y7001xrigc.public.elasticsearch.aliyuncs.com:9200

  application:
    name: cloud-manager-web-server


mybatis:
  # 指定映射配置文件路径
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka